package com.floatai.atk

import java.io.File

/**
 * 在设备本地生成一个最小可构建的 APK 项目脚手架。
 *
 * 生成的目录结构：
 *  <root>/build.gradle
 *  <root>/settings.gradle
 *  <root>/gradle.properties
 *  <root>/local.properties   (sdk.dir 占位)
 *  <root>/app/build.gradle
 *  <root>/app/proguard-rules.pro
 *  <root>/app/src/main/AndroidManifest.xml
 *  <root>/app/src/main/java/<pkg-path>/MainActivity.kt
 *  <root>/app/src/main/res/values/{strings,themes,colors}.xml
 */
object AtkScaffold {

    fun create(
        root: File,
        projectName: String,
        packageName: String
    ): File {
        require(isValidPackage(packageName)) { "Invalid package name: $packageName" }
        val safeName = projectName.replace(Regex("[^A-Za-z0-9_\\-]"), "_")
        val target = File(root, safeName).apply { mkdirs() }
        File(target, "build.gradle").writeText(rootBuildGradle())
        File(target, "settings.gradle").writeText(settingsGradle(safeName))
        File(target, "gradle.properties").writeText(gradleProperties())
        File(target, "local.properties").writeText("# sdk.dir=/path/to/android-sdk\n")

        val appDir = File(target, "app").apply { mkdirs() }
        File(appDir, "build.gradle").writeText(appBuildGradle(packageName))
        File(appDir, "proguard-rules.pro").writeText("# generated by FloatAI ATK\n")

        val srcDir = File(appDir, "src/main").apply { mkdirs() }
        File(srcDir, "AndroidManifest.xml").writeText(manifest(packageName))
        val pkgPath = packageName.replace('.', '/')
        val javaDir = File(srcDir, "java/$pkgPath").apply { mkdirs() }
        File(javaDir, "MainActivity.kt").writeText(mainActivityKt(packageName))
        val resDir = File(srcDir, "res/values").apply { mkdirs() }
        File(resDir, "strings.xml").writeText(stringsXml(projectName))
        File(resDir, "themes.xml").writeText(themesXml())
        File(resDir, "colors.xml").writeText(colorsXml())
        return target
    }

    private fun isValidPackage(pkg: String): Boolean =
        Regex("^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)+$").matches(pkg)

    private fun rootBuildGradle() = """
        plugins {
            id 'com.android.application' version '8.2.2' apply false
            id 'org.jetbrains.kotlin.android' version '1.9.22' apply false
        }
    """.trimIndent()

    private fun settingsGradle(name: String) = """
        pluginManagement {
            repositories {
                google()
                mavenCentral()
                gradlePluginPortal()
            }
        }
        dependencyResolutionManagement {
            repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
            repositories { google(); mavenCentral() }
        }
        rootProject.name = "$name"
        include ':app'
    """.trimIndent()

    private fun gradleProperties() = """
        android.useAndroidX=true
        android.nonTransitiveRClass=true
        org.gradle.jvmargs=-Xmx2048m
        kotlin.code.style=official
    """.trimIndent()

    private fun appBuildGradle(pkg: String) = """
        plugins {
            id 'com.android.application'
            id 'org.jetbrains.kotlin.android'
        }
        android {
            namespace '$pkg'
            compileSdk 34
            defaultConfig {
                applicationId '$pkg'
                minSdk 26
                targetSdk 34
                versionCode 1
                versionName "1.0"
            }
            buildTypes {
                debug { }
                release {
                    minifyEnabled false
                    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                }
            }
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_17
                targetCompatibility JavaVersion.VERSION_17
            }
            kotlinOptions { jvmTarget = '17' }
        }
        dependencies {
            implementation 'androidx.core:core-ktx:1.12.0'
            implementation 'androidx.appcompat:appcompat:1.6.1'
            implementation 'com.google.android.material:material:1.11.0'
        }
    """.trimIndent()

    private fun manifest(pkg: String) = """
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android">
            <uses-permission android:name="android.permission.INTERNET" />
            <application
                android:label="@string/app_name"
                android:theme="@style/Theme.App">
                <activity android:name=".MainActivity" android:exported="true">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
            </application>
        </manifest>
    """.trimIndent()

    private fun mainActivityKt(pkg: String) = """
        package $pkg

        import android.os.Bundle
        import androidx.appcompat.app.AppCompatActivity
        import android.widget.TextView

        class MainActivity : AppCompatActivity() {
            override fun onCreate(savedInstanceState: Bundle?) {
                super.onCreate(savedInstanceState)
                setContentView(TextView(this).apply {
                    text = "Hello from FloatAI ATK!"
                    textSize = 20f
                })
            }
        }
    """.trimIndent()

    private fun stringsXml(name: String) = """
        <?xml version="1.0" encoding="utf-8"?>
        <resources>
            <string name="app_name">$name</string>
        </resources>
    """.trimIndent()

    private fun themesXml() = """
        <?xml version="1.0" encoding="utf-8"?>
        <resources>
            <style name="Theme.App" parent="Theme.Material3.DayNight.NoActionBar" />
        </resources>
    """.trimIndent()

    private fun colorsXml() = """
        <?xml version="1.0" encoding="utf-8"?>
        <resources>
            <color name="primary">#5E5CE6</color>
        </resources>
    """.trimIndent()
}
