package com.bskai.ui.screens.agreements

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.ArrowBack
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun TermsScreen(onBack: () -> Unit) {
    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Terms of Service", fontWeight = FontWeight.SemiBold) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.Outlined.ArrowBack, contentDescription = "Back")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = Color.Transparent
                )
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .verticalScroll(rememberScrollState())
                .padding(horizontal = 16.dp)
        ) {
            Spacer(Modifier.height(16.dp))
            Text(
                "BSK AI Terms of Service",
                style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Bold),
                color = MaterialTheme.colorScheme.onBackground
            )
            Spacer(Modifier.height(8.dp))
            Text(
                "Last updated: January 2026",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
            Spacer(Modifier.height(16.dp))
            AgreementSection(title = "1. Scope of Agreement") {
                Text(
                    "Welcome to BSK AI (the \"Application\"). These Terms of Service govern your use of the Application. By downloading, installing, registering, logging in, or using the Application, you acknowledge that you have read and agree to be bound by these Terms in their entirety.",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }
            AgreementSection(title = "2. Services Provided") {
                Text(
                    "The Application provides AI-powered coding assistance including but not limited to: code generation, code review, project management, and terminal command execution. Services are delivered through integration with external APIs or local model services.",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }
            AgreementSection(title = "3. User Obligations") {
                Text(
                    "1. You must ensure your use of the Application complies with applicable laws and regulations.\n" +
                    "2. You must not use the Application for any illegal or unauthorized purpose.\n" +
                    "3. You are responsible for safeguarding your device and preventing unauthorized access.\n" +
                    "4. You are solely responsible for any output generated by the Application.",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }
            AgreementSection(title = "4. Intellectual Property") {
                Text(
                    "All content of the Application including text, images, icons, interface designs, and code is protected by intellectual property laws. You may not copy, distribute, display, link, scrape, or otherwise use any Application content without prior written consent.",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }
            AgreementSection(title = "5. Disclaimer of Warranties") {
                Text(
                    "1. The Application is provided \"as is\" without warranty of any kind.\n" +
                    "2. We do not guarantee that the Application will meet your requirements or be uninterrupted.\n" +
                    "3. You understand and agree that the Application provides tool services only, and we bear no responsibility for your code, projects, or any other content.",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }
            AgreementSection(title = "6. Limitation of Liability") {
                Text(
                    "To the maximum extent permitted by law, the Application shall not be liable for any indirect, incidental, special, punitive, or consequential damages arising from your use of the Application.",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }
            AgreementSection(title = "7. Modifications") {
                Text(
                    "We reserve the right to modify these Terms at any time. Modified Terms will be published within the Application. If you do not agree to modified Terms, you must cease using the Application immediately. Continued use constitutes acceptance of modified Terms.",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }
            AgreementSection(title = "8. Contact") {
                Text(
                    "If you have questions about these Terms, please contact us through the feedback channel in the app settings.",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }
            Spacer(Modifier.height(32.dp))
        }
    }
}

@Composable
private fun AgreementSection(title: String, content: @Composable () -> Unit) {
    Column(modifier = Modifier.padding(vertical = 12.dp)) {
        Text(
            title,
            style = MaterialTheme.typography.titleSmall.copy(fontWeight = FontWeight.Bold),
            color = MaterialTheme.colorScheme.primary
        )
        Spacer(Modifier.height(6.dp))
        content()
    }
}
