package com.floatai.ui.screens.atk

import android.app.Application
import android.content.Context
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import androidx.lifecycle.viewmodel.initializer
import androidx.lifecycle.viewmodel.viewModelFactory
import com.floatai.App
import com.floatai.atk.AtkAiDiagnose
import com.floatai.atk.AtkBuilder
import com.floatai.atk.AtkGithubPublisher
import com.floatai.atk.AtkScaffold
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File

data class AtkUiState(
    val projectDir: String = "",
    val logs: String = "",
    val terminalCmd: String = "",
    val building: Boolean = false,
    val publishing: Boolean = false,
    val lastApk: String = "",
    val message: String = "",
    val aiAnswer: String = "",
    val projectName: String = "MyApp",
    val packageName: String = "com.example.myapp",
    val repoName: String = "MyApp",
    val repoDesc: String = "Generated by FloatAI ATK",
    val repoPrivate: Boolean = false
)

class AtkViewModel(private val app: App) : AndroidViewModel(app) {

    private val _state = MutableStateFlow(AtkUiState())
    val state: StateFlow<AtkUiState> = _state.asStateFlow()

    fun setProjectName(v: String) = _state.update { it.copy(projectName = v) }
    fun setPackageName(v: String) = _state.update { it.copy(packageName = v) }
    fun setRepoName(v: String) = _state.update { it.copy(repoName = v) }
    fun setRepoDesc(v: String) = _state.update { it.copy(repoDesc = v) }
    fun setRepoPrivate(v: Boolean) = _state.update { it.copy(repoPrivate = v) }
    fun setTerminalCmd(v: String) = _state.update { it.copy(terminalCmd = v) }

    private fun projectsRoot(): File {
        val dir = File(app.filesDir, "atk/projects")
        if (!dir.exists()) dir.mkdirs()
        return dir
    }

    fun currentProjectDir(): File? = _state.value.projectDir
        .takeIf { it.isNotBlank() }
        ?.let { File(it) }
        ?.takeIf { it.exists() }

    fun scaffold() {
        viewModelScope.launch(Dispatchers.IO) {
            try {
                val dir = AtkScaffold.create(
                    root = projectsRoot(),
                    projectName = _state.value.projectName,
                    packageName = _state.value.packageName
                )
                _state.update {
                    it.copy(
                        projectDir = dir.absolutePath,
                        message = "脚手架已生成：${dir.absolutePath}"
                    )
                }
            } catch (e: Exception) {
                _state.update { it.copy(message = "脚手架生成失败：${e.message}") }
            }
        }
    }

    fun build(task: String) {
        val dir = currentProjectDir() ?: return
        _state.update { it.copy(building = true, logs = "", message = "开始构建…") }
        viewModelScope.launch(Dispatchers.IO) {
            val result = AtkBuilder.build(dir, task) { line ->
                _state.update { it.copy(logs = (it.logs + line + "\n").takeLast(50_000)) }
            }
            _state.update {
                when (result) {
                    is AtkBuilder.Result.Success -> it.copy(
                        building = false,
                        lastApk = result.apk.absolutePath,
                        message = "构建完成：${result.apk.absolutePath}"
                    )
                    is AtkBuilder.Result.Failure -> it.copy(
                        building = false,
                        message = "构建失败（exit=${result.exitCode}），查看日志或用 AI 诊断"
                    )
                }
            }
        }
    }

    fun publish() {
        val dir = currentProjectDir() ?: return
        val s = _state.value
        val token = app.settingsRepository.settings.value.githubToken
        if (token.isBlank()) {
            _state.update { it.copy(message = "请先在设置页配置 GitHub Token") }
            return
        }
        val apk = s.lastApk.takeIf { it.isNotBlank() }?.let { File(it) }?.takeIf { it.exists() }
        _state.update { it.copy(publishing = true, message = "发布中…") }
        viewModelScope.launch(Dispatchers.IO) {
            val result = AtkGithubPublisher.publish(
                token = token,
                repoName = s.repoName,
                description = s.repoDesc,
                isPrivate = s.repoPrivate,
                projectDir = dir,
                apkFile = apk
            )
            _state.update {
                when (result) {
                    is AtkGithubPublisher.Result.Success -> it.copy(
                        publishing = false,
                        message = "已发布：${result.repoUrl}"
                    )
                    is AtkGithubPublisher.Result.Failure -> it.copy(
                        publishing = false,
                        message = "发布失败（${result.step}）：${result.message}"
                    )
                }
            }
        }
    }

    fun aiDiagnose() {
        val logs = _state.value.logs
        if (logs.isBlank()) {
            _state.update { it.copy(message = "没有构建日志可诊断") }
            return
        }
        val config = app.settingsRepository.apiConfig.value
        if (config.baseUrl.isBlank() || config.apiKey.isBlank()) {
            _state.update { it.copy(message = "请先在 AI 对话页配置 API") }
            return
        }
        viewModelScope.launch {
            _state.update { it.copy(aiAnswer = "AI 诊断中…") }
            val answer = withContext(Dispatchers.IO) {
                AtkAiDiagnose.diagnose(config, logs, lang = "zh")
            }
            _state.update { it.copy(aiAnswer = answer) }
        }
    }

    fun runTerminal() {
        val cmd = _state.value.terminalCmd.trim()
        if (cmd.isEmpty()) return
        _state.update { it.copy(logs = it.logs + "\n[terminal] $ $cmd\n") }
        viewModelScope.launch(Dispatchers.IO) {
            val process = ProcessBuilder("/system/bin/sh", "-c", cmd).start()
            val dir = currentProjectDir() ?: app.filesDir
            process.inputStream.bufferedReader().useLines { lines ->
                lines.forEach { line ->
                    _state.update { it.copy(logs = (it.logs + line + "\n").takeLast(50_000)) }
                }
            }
            process.errorStream.bufferedReader().useLines { lines ->
                lines.forEach { line ->
                    _state.update { it.copy(logs = (it.logs + line + "\n").takeLast(50_000)) }
                }
            }
            val code = process.waitFor()
            _state.update { it.copy(logs = it.logs + "[terminal] exit $code\n") }
        }
    }

    fun clearLog() = _state.update { it.copy(logs = "") }
    fun clearMessage() = _state.update { it.copy(message = "") }
    fun clearAi() = _state.update { it.copy(aiAnswer = "") }

    companion object {
        fun factory(app: App): ViewModelProvider.Factory = viewModelFactory {
            initializer { AtkViewModel(app) }
        }
    }
}
